import { Property } from './types';

export const PROPERTIES: Property[] = [
  {
    id: '1',
    title: 'Modern Villa in Lago Mar Beach',
    price: 450000,
    location: 'Maracaibo',
    type: 'House',
    beds: 4,
    baths: 4,
    sqft: 3500,
    image: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&q=80&w=800',
    description: 'Stunning modern villa located in the exclusive Lago Mar Beach club. Features include a private pool, smart home technology, and direct access to the lake view.',
    featured: true,
  },
  {
    id: '2',
    title: 'Luxury Apartment in Tierra Negra',
    price: 180000,
    location: 'Maracaibo',
    type: 'Apartment',
    beds: 3,
    baths: 2,
    sqft: 1800,
    image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&q=80&w=800',
    description: 'High-floor apartment with panoramic views of the city. Recently renovated with marble floors and Italian kitchen. Building offers 24/7 security and power generator.',
    featured: true,
  },
  {
    id: '3',
    title: 'Commercial Space in Costa Mall',
    price: 350000,
    location: 'Cabimas',
    type: 'Commercial',
    beds: 0,
    baths: 1,
    sqft: 1200,
    image: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&q=80&w=800',
    description: 'Prime retail location in the busiest corridor of Costa Mall. Perfect for a boutique or showroom. High foot traffic area.',
    featured: true,
  },
  {
    id: '4',
    title: 'Colonial Home in Santa Rita center',
    price: 120000,
    location: 'Santa Rita',
    type: 'House',
    beds: 5,
    baths: 3,
    sqft: 2800,
    image: 'https://images.unsplash.com/photo-1518780664697-55e3ad937233?auto=format&fit=crop&q=80&w=800',
    description: 'Beautifully restored colonial-style home in the heart of Santa Rita. Spacious internal courtyard and ample parking.',
    featured: false,
  },
  {
    id: '5',
    title: 'Industrial Plot in Ciudad Ojeda',
    price: 850000,
    location: 'Ciudad Ojeda',
    type: 'Land',
    beds: 0,
    baths: 0,
    sqft: 45000,
    image: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&q=80&w=800',
    description: 'Large industrial land perfect for logistics or manufacturing. Easy access to the Intercommunal Avenue.',
    featured: false,
  },
  {
    id: '6',
    title: 'Cozy Family Home in San Francisco',
    price: 95000,
    location: 'San Francisco',
    type: 'House',
    beds: 3,
    baths: 2,
    sqft: 1500,
    image: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b91d?auto=format&fit=crop&q=80&w=800',
    description: 'Affordable and secure family home in a gated community in San Francisco. Close to the bridge and main avenues.',
    featured: true,
  }
];

export const ABOUT_CONTENT = {
  mission: "We are dedicated to redefining the real estate experience in Zulia through integrity, innovation, and unparalleled service. Our mission is to connect clients with properties that perfectly match their lifestyle and investment goals.",
  vision: "To be the most trusted and prestigious real estate agency in Western Venezuela, recognized globally for our exclusive portfolio and our commitment to excellence in every transaction.",
  history: "Founded in 2010, Lago Realty established itself as a pioneer in the Zulian luxury real estate market. Over the past decade, we have facilitated over $500 million in property transactions, building a reputation for discretion and results."
};
